### ISSUE TITLE
Readme.md spelling issue...

### ISSUE THREAD

**Issue by SalvorinFex** [mikeckennedy/write-pythonic-code-demos#9]
You have this under:  **What is Pythonic code and why does it matter?**

> Most importantly perhaps, you are writing code that is easily read and understood by your follow and senior Python developers.

Pretty sure that is supposed to be "...understood by your FELLOW and senior Python developers."

**Comment by mikeckennedy** [comment]
Yikes, it should be! Thanks.

**Comment by mikeckennedy** [comment]
Fixed, thanks.
